# Generated by Django 4.2.6 on 2023-10-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_delete_programlang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
